---
- name: Speedtest-Tracker Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ speedtest_data_directory }}/config"

- name: Remove old Speedtest-Tracker Docker Container
  docker_container:
    name: speedtest_tracker
    state: absent

- name: Speedtest-Tracker Docker Container
  docker_container:
    name: speedtest-tracker
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    pull: true
    volumes:
      - "{{ speedtest_data_directory }}/config:/config:rw"
    ports:
      - "{{ speedtest_tracker_http_port }}:80"
      - "{{ speedtest_tracker_https_port }}:443"
    env:
      #OOKLA_EULA_GDPR: "true"
      TZ: "{{ ansible_timezone }}"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: "1g"
    labels:
      traefik.enable: "{{ speedtest_tracker_available_externally | string }}"
      traefik.http.routers.speedtest_tracker.rule: "Host(`{{ speedtest_tracker_hostname }}.{{ ansible_www_domain }}`)"
      traefik.http.routers.speedtest_tracker.tls.certresolver: "letsencrypt"
      traefik.http.routers.speedtest_tracker.tls.domains[0].main: "{{ ansible_www_domain }}"
      traefik.http.routers.speedtest_tracker.tls.domains[0].sans: "*.{{ ansible_www_domain }}"
      traefik.http.services.speedtest_tracker.loadbalancer.server.port: "80"
      traefik.http.routers.speedtest_tracker.middlewares: traefik-forward-auth
