---
- name: Create Sabnzbd Data Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sabnzbd_data_directory }}"

- name: Sabnzbd
  docker_container:
    name: sabnzbd
    image: linuxserver/sabnzbd
    pull: true
    volumes:
      - "{{ sabnzbd_data_directory }}:/config:rw"
      - "{{ sabnzbd_downloads_directory }}:/downloads"
      - "{{ sabnzbd_incomplete_directory }}:/incomplete-downloads"
    ports:
      - "{{ sabnzbd_port }}:8080"
    env:
      TZ: "{{ ansible_timezone }}"
      PUID: "{{ sabnzbd_user_id }}"
      PGID: "{{ sabnzbd_group_id }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ sabnzbd_available_externally | string }}"
      traefik.http.routers.sabnzbd.rule: "Host(`{{ sabnzbd_hostname }}.{{ ansible_www_domain }}`)"
      traefik.http.routers.sabnzbd.tls.certresolver: "letsencrypt"
      traefik.http.routers.sabnzbd.tls.domains[0].main: "{{ ansible_www_domain }}"
      traefik.http.routers.sabnzbd.tls.domains[0].sans: "*.{{ ansible_www_domain }}"
      traefik.http.services.sabnzbd.loadbalancer.server.port: "8080"
