---
#? ansible-galaxy install -r requirements.yml --force
- name: geerlingguy.docker
  version: 6.1.0

- name: bertvv.samba
  version: v2.7.1

- name: geerlingguy.nfs
  version: 2.0.0

- name: ansible.posix
  version: 1.4.0
