---
- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
  register: result
  until: result is succeeded

- name: Remove docker-py python module
  pip:
    name: docker-py
    state: absent
  register: result
  until: result is succeeded

- name: Install docker python module
  pip:
    name: docker
    state: present
  register: result
  until: result is succeeded

- name: Create Docker home directory
  file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory

- name: Add user account to Docker group
  user:
    name: "{{ ansible_nas_user }}"
    groups: docker
    append: yes

- name: Generate Docker daemon.json
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_json | to_nice_json }}"
  register: docker_config

- name: Create override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'  # Adjust the mode as needed
    owner: root
    group: root

- name: Create or update the override.conf file
  lineinfile:
    path: /etc/systemd/system/docker.service.d/override.conf
    create: yes
    line: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd

- name: Reload daemons
  ansible.builtin.systemd:
    daemon_reload: true
  when: docker_config.changed

- name: Restart Docker # noqa no-handler
  service:
    name: docker
    state: restarted
  when: docker_config.changed
