---
speedtest_tracker_enabled: false
speedtest_tracker_available_externally: false

# directories
speedtest_data_directory: "{{ docker_home }}/speedtest_tracker/"

# uid / gid
speedtest_tracker_user_id: "0"
speedtest_tracker_group_id: "0"

# network
speedtest_tracker_http_port: "8080"
speedtest_tracker_https_port: "8443"
speedtest_tracker_hostname: "speedtest-tracker"

# specs
speedtest_tracker_memory: 1g
