---
- name: Create Transmission Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ transmission_config_directory }}"
    - "{{ transmission_download_directory }}"
    - "{{ transmission_watch_directory }}"

- name: Transmission with VPN
  docker_container:
    name: transmission-openvpn
    image: haugene/transmission-openvpn
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ transmission_download_directory }}:/downloads:rw"
      - "{{ transmission_config_directory }}:/config:rw"
      - "{{ transmission_watch_directory }}:/watch:rw"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ transmission_openvpn_webui_port }}:9091"
      - "{{ transmission_openvpn_external_port }}:51413"
      - "{{ transmission_openvpn_external_port }}:51413/udp"
      - "{{ transmission_openvpn_proxy_port }}:3128"
    env:
      TRANSMISSION_HOME: "/config"
      TRANSMISSION_DOWNLOAD_DIR: "/downloads"
      TRANSMISSION_INCOMPLETE_DIR: "/downloads/.incomplete"
      TRANSMISSION_WATCH_DIR: "/watch"
      TRANSMISSION_RATIO_LIMIT: "{{ transmission_openvpn_ratio_limit }}"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "{{ transmission_openvpn_ratio_limit_enabled | string }}"
      ##* update me, if your provider is different ==>
      ##? ref: https://github.com/haugene/docker-transmission-openvpn/issues/1172#issuecomment-623982281
      OPENVPN_USERNAME: "{{ openvpn_username }}"
      OPENVPN_PASSWORD: "{{ openvpn_password }}"
      OPENVPN_PROVIDER: NORDVPN
      NORDVPN_COUNTRY: CH
      NORDVPN_PROTOCOL: tcp
      NORDVPN_CATEGORY: P2P
      OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"                            # https://api.nordvpn.com/v1/servers/countries
      ##* <== update me, if your provider is different
      WEBPROXY_ENABLED: "true"
      WEBPROXY_PORT: "3128"
      PUID: "{{ transmission_openvpn_user_id }}"
      PGID: "{{ transmission_openvpn_group_id }}"
      LOCAL_NETWORK: "{{ transmission_openvpn_local_network }}"
      ENABLE_UFW: "false"
    devices:
      - /dev/net/tun
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
    memory: "{{ transmission_openvpn_memory }}"
    labels:
      traefik.enable: "{{ transmission_openvpn_available_externally | string }}"
      traefik.http.routers.transmission_openvpn.rule: "Host(`{{ transmission_openvpn_hostname }}.{{ ansible_www_domain }}`)"
      traefik.http.routers.transmission_openvpn.tls.certresolver: "letsencrypt"
      traefik.http.routers.transmission_openvpn.tls.domains[0].main: "{{ ansible_www_domain }}"
      traefik.http.routers.transmission_openvpn.tls.domains[0].sans: "*.{{ ansible_www_domain }}"
      traefik.http.services.transmission_openvpn.loadbalancer.server.port: "9091"
