---
##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

###
### Example options
###

ansible_hostname: yourserver
ansible_timezone: Europe/London
ansible_user: youruser                    # Will be added to the docker group to give user command line access to docker
ansible_www_email: your@email                 # Your email and domain, used for Let's Encrypt SSL certs
ansible_www_domain: yourdomain                # Applications will have subdomain SSL certificates created if Traefik is enabled, e.g. ansible-nas.<your-domain>, nextcloud.<your-domain>
ansible_python_interpreter: /usr/bin/python3  # What version of python ansible should use on target system (path to spesific binary)
docker_home: /home/youruser/docker            # docker data
samba_shares_root: /mnt/Media                 # media data
traefik_enabled: true
docker_backup: /mnt/Backup

###
### Secrets
###

cloudflare_dns_api_token: yourapitoken
traefik_google_client_id: yourclientid                                            # client ID from the Google project
traefik_google_client_secret: yourclientsecret                                    # client secret from the Google project
traefik_forwardauth_secret: yourcookiesecret                                      # cookie secret
traefik_forwardauth_whitelist: your@email                                         # enabled email
plex_claim: claim-your claim                                                      # https://www.plex.tv/claim/
tailscale_auth_key: your-tailscale-auth-key                                       # https://tailscale.com/kb/1085/auth-keys/
slack_hook: https://hooks.slack.com/services/your-hook-token                      # https://containrrr.dev/watchtower/notifications/  # https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook
openvpn_username: yourusername
openvpn_password: yourpassword
tunnel_token:

###
### APPLICATION - overrides
###

### I prefer homepage - https://github.com/benphelps/homepage/ - as a front end

### Application available externally, so I also put this behind Google Oauth2
homepage_enabled: true                        # enable the actual application
homepage_available_externally: true           # make it available externally

### Application available externally, so I also put this behind Google Oauth2
portainer_enabled: true
portainer_available_externally: true

### Application available externally (consider adding oauth block in ansible-nas-docker/roles/sonarr/tasks/main.yml)
sonarr_enabled: true
sonarr_available_externally: true

## Application available externally (consider adding oauth block in ansible-nas-docker/roles/radarr/tasks/main.yml)
radarr_enabled: true
radarr_available_externally: true

## Application is not available externally
transmission_enabled: true
transmission_available_externally: false

## Application uses Plex-authentication, therefore Oauth omited
overseerr_enabled: true
overseerr_available_externally: true

## Application uses Plex-authentication, therefore Oauth omited
plex_enabled: true
plex_available_externally: true
