---
- name: Create "{{ ansible_create_group }}" group
  group:
    name: "{{ ansible_create_group }}"
    state: present

- name: Create "{{ ansible_create_user }}" user
  user:
    name: "{{ ansible_create_user }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: ansible-nas
    shell: /usr/sbin/nologin
